# Generated by Django 4.2.17 on 2026-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_authors_book_author_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
